version: '3.7'

services:
  db:
    image: postgres:12.2-alpine
    restart: always
    container_name: library_management_db
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    networks:
      - api_network
    volumes:
      - ./scripts/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./db:/var/lib/postgresql/data/
  api_server:
    build: ./
    restart: always
    container_name: library_management_api_server
    command: sh -c "python /app/manage.py makemigrations && python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:8000"
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app:cached
    expose:
      - 8000
    ports:
      - '8083:8000'
    networks:
      - api_network
    depends_on:
      - db

networks:
  api_network:
    name: library_management_system
