# Generated by Django 3.1.2 on 2021-03-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210309_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
